create table aoc_day02 (
	seq int generated by default as identity primary key
	, direction varchar(18)
	, units int );
create index ix_day02_direction on aoc_day02 (direction, units) allow reverse scans;
