drop table aoc_day04_picker;
create table if not exists aoc_day04_picker (
	seq int generated by default as identity primary key
	, num_selected int not null
	, processed smallint not null default 0
);
drop table aoc_day04_boards;
create table if not exists aoc_day04_boards (
	seq int generated by default as identity primary key
	, game_num int not null
	, row_num smallint not null
    , col_num smallint not null
    , value int not null
    , picked smallint not null default 0
);
create unique index ix_aoc_day04_boards_position on aoc_day04_boards (game_num, row_num, col_num) include (picked) allow reverse scans;
create index ix_aoc_day04_boards_value on aoc_day04_boards ( value ) allow reverse scans;
